application: erikspuns
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /webapp
  static_dir: webapp
- url: /css
  static_dir: css
- url: /js
  static_dir: js
- url: /img
  static_dir: img
- url: /.*
  script: erikspun.app

libraries:
- name: jinja2
  version: latest